import streamlit as st
import time
from config.config import ENV

st.set_page_config(
    page_title="DriftShield",
    page_icon="🛡️",
    layout="wide"
)

st.toast("👈 Use the sidebar to access all pages.")

st.markdown(
    f"""
    # 🚀 DriftShield

### ML-Powered Loan Risk Assessment & Monitoring Platform

DriftShield is an end-to-end Machine Learning application designed to simulate how a financial institution might evaluate loan applications, manage deployed models, and monitor model reliability in production environments.

The project goes beyond simple loan approval predictions by combining risk assessment, explainability, model management, and data drift monitoring into a single platform.

---

## 🎯 What Does DriftShield Do?

Given a customer's financial profile, DriftShield:

* Predicts the probability of loan default.
* Identifies key risk factors affecting repayment ability.
* Highlights positive financial indicators.
* Recommends safer loan configurations when risk is too high.
* Generates an AI-powered assessment summary.
* Monitors production data for drift.
* Supports model versioning and activation without redeployment.

---

## 🔍 Core Features

### 1. Loan Default Prediction

Predicts the likelihood that a customer may default on a loan based on financial and demographic information.

### 2. Risk & Strength Analysis

Identifies factors that increase or decrease lending risk, helping explain why a prediction was made.

Examples include:

* Credit score
* Income level
* Existing loans
* EMI burden
* Loan-to-income ratio
* Employment profile

### 3. Smart Loan Recommendations

Instead of only rejecting risky applications, the system searches for safer loan amounts and repayment tenures that may reduce risk to acceptable levels.

### 4. AI-Powered Assessment

An LLM generates a concise banking-style explanation based on model outputs, risk indicators, and recommendation results.

> The AI does not make the decision. It only explains the results generated by the machine learning model and business rules.

---

## 📊 Data Drift Monitoring

Machine learning models can become less reliable when production data starts to differ from training data.

DriftShield uses Evidently AI to:

* Compare training and production datasets
* Detect feature-level drift
* Generate visual drift reports
* Produce AI-assisted drift summaries

This helps identify situations where model retraining may be required.

---

## 🗂 Model Registry

The platform includes a lightweight model registry for managing multiple model versions.

Supported capabilities:

* Upload model artifacts
* Upload scaler files
* Upload evaluation metrics
* Upload reference datasets
* Activate models dynamically
* Track model metadata and versions

This allows model switching without restarting or redeploying the application.

---

## ⚙️ Application Workflow

Customer Data

⬇️

Prediction Engine

⬇️

Risk Analysis

⬇️

Loan Recommendation Engine

⬇️

AI Assessment Generation

⬇️

Prediction Logging

⬇️

Data Drift Monitoring

⬇️

Model Management & Continuous Improvement

---

## 📁 Application Modules

### Prediction

Run loan default predictions, review risk factors, and receive AI-generated assessments.

### Drift Monitoring

Generate drift reports, review feature drift, and analyze production data health.

### Model Registry

Manage model versions, activate models, and maintain deployment-ready artifacts.

---

## 🛠 Technology Stack

**Machine Learning**

* XGBoost
* Scikit-Learn
* Pandas
* NumPy

**Backend**

* FastAPI
* PostgreSQL
* SQLAlchemy

**Monitoring**

* Evidently AI

**AI Integration**

* Groq API

**Frontend**

* Streamlit

**DevOps**

* Docker
* GitHub Actions
* AWS EC2

---

## 🔗 Additional Resources

### Backend Repository

[View Backend Source Code](https://github.com/mdalishekh/DriftShield)

### Frontend Repository

[View Frontend Source Code](https://github.com/mdalishekh/DriftShield-Frontend)

### API Documentation

[Swagger / OpenAPI Docs]({ENV.BASE_URL}/drift-docs)

### Project Documentation

Detailed architecture, implementation details, deployment workflow, and technical decisions are available in the project repository.

---

## 📌 Note

DriftShield is a portfolio project created to demonstrate practical Machine Learning Engineering and MLOps concepts, including model deployment, model versioning, monitoring, explainability, and production-oriented workflows.

---

## 👨‍💻 About

- [Portfolio Webpage](https://mdalishekh.in/)
- [LinkedIn](https://www.linkedin.com/in/mdalishekh/)
- [GitHub](https://github.com/mdalishekh)

"""
)

time.sleep(5)
st.toast("👈 Use the sidebar to access all pages.")
